ALTER TABLE `metrics_1d` ADD `rx_bytes` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `rx_packets` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `rx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `rx_errors` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `d_rx_bytes` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `d_rx_packets` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `d_rx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `d_rx_errors` integer;--> statement-breakpoint
CREATE INDEX `metrics_1d_controller_ts` ON `metrics_1d` (`controller_id`,`ts`);--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `rx_bytes` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `rx_packets` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `rx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `rx_errors` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `d_rx_bytes` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `d_rx_packets` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `d_rx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `d_rx_errors` integer;--> statement-breakpoint
CREATE INDEX `metrics_1h_controller_ts` ON `metrics_1h` (`controller_id`,`ts`);--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `rx_bytes` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `rx_packets` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `rx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `rx_errors` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `d_rx_bytes` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `d_rx_packets` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `d_rx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `d_rx_errors` integer;--> statement-breakpoint
CREATE INDEX `metrics_5m_controller_ts` ON `metrics_5m` (`controller_id`,`ts`);--> statement-breakpoint
CREATE INDEX `devices_alias_idx` ON `devices` (`display_alias`);