ALTER TABLE `devices` ADD `version` text;--> statement-breakpoint
ALTER TABLE `devices` ADD `serial` text;--> statement-breakpoint
ALTER TABLE `devices` ADD `state` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `wifi_tx_attempts` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `wifi_tx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `rx_crypts` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `mac_filter_rejections` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `num_roam_events` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `d_wifi_tx_attempts` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `d_wifi_tx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `d_rx_crypts` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `d_mac_filter_rejections` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `d_num_roam_events` integer;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `cpu_pct` real;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `mem_pct` real;--> statement-breakpoint
ALTER TABLE `metrics_1d` ADD `uptime_sec` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `wifi_tx_attempts` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `wifi_tx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `rx_crypts` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `mac_filter_rejections` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `num_roam_events` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `d_wifi_tx_attempts` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `d_wifi_tx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `d_rx_crypts` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `d_mac_filter_rejections` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `d_num_roam_events` integer;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `cpu_pct` real;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `mem_pct` real;--> statement-breakpoint
ALTER TABLE `metrics_1h` ADD `uptime_sec` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `wifi_tx_attempts` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `wifi_tx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `rx_crypts` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `mac_filter_rejections` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `num_roam_events` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `d_wifi_tx_attempts` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `d_wifi_tx_dropped` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `d_rx_crypts` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `d_mac_filter_rejections` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `d_num_roam_events` integer;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `cpu_pct` real;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `mem_pct` real;--> statement-breakpoint
ALTER TABLE `metrics_5m` ADD `uptime_sec` integer;